### ISSUE TITLE
.

### ISSUE THREAD

**Issue by pvnotpv** [1337w0rm/YeetMeet#22]
nothing

**Comment by 1337w0rm** [comment]
After running `chromium.py` go to your telegram bot and send /mlogin to login on meet, keep it running until you get `Logged In` message from the bot on telegram. Then you can send /meet meeting_url to join meet meetings.

**Comment by pvnotpv** [comment]
When I send /mlogin to the bot after running python3 chromium.py ,it does nothing

**Comment by 1337w0rm** [comment]
> When I send /mlogin to the bot after running python3 chromium.py ,it does nothing

Do you get any error ? Was chromium.py running when you sent /mlogin ? Share your config.py

**Comment by VikingStudiosZ9** [comment]
My config.py ---
import os
class Config(object):
    BOT_TOKEN = os.environ.get('BOT_TOKEN', '1434075277:AAFPFES_*****************MFY52UISZ-c')
    GUSERNAME = os.environ.get('GUSER_NAME', '9100@*****.ac.in')
    GPASSWORD = os.environ.get('GPASSWORD', '************3')
    SCHEDULE = os.environ.get('SCHEDULE', False)
    USERID = os.environ.get('vik******_***_z')

When I run chromium.py (python3 chromium.py)
OK, so the browser executes and when I type /mlogin , the terminal shows me this error

┌──(vikingstudiosz㉿Kali)-[~/Desktop/YeetMeet]
└─$ python3 chromium.py                                                                                                                                     148 ⨯ 1 ⚙
2020-12-03 11:40:58,523 - root - INFO - Bot started
2020-12-03 11:41:10,738 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/vikingstudiosz/.local/lib/python3.8/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/vikingstudiosz/Desktop/YeetMeet/bot/meet_login.py", line 16, in mlogin
    context.bot.send_chat_action(chat_id=userId, action=ChatAction.TYPING)
  File "<decorator-gen-20>", line 2, in send_chat_action
  File "/home/vikingstudiosz/.local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/vikingstudiosz/.local/lib/python3.8/site-packages/telegram/bot.py", line 1482, in send_chat_action
    result = self._request.post(url, data, timeout=timeout)
  File "/home/vikingstudiosz/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/home/vikingstudiosz/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 245, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found

'Chat not found' ?? This is the output that comes when i type /mlogin in telegram

**Comment by 1337w0rm** [comment]
You haven't set USERID in config.py correctly. See the guide on how to get UserID. It will be 9 digit number.

**Comment by VikingStudiosZ9** [comment]
Oh , yes thanks a lot mahn , it worked , now when I am uploading it to heroku , first I should create an app
then set that chrome buld pack after that what should i do

**Comment by 1337w0rm** [comment]
Read README.md it have all the instructions.

**Comment by VikingStudiosZ9** [comment]
Mahn i don't know how to thank you   i just can't believe it , thanks a lottt ,* 100000000000000000000
