### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eyjge** [1337w0rm/YeetMeet#41]
When I run `python chromium.py` in my server,it shows this error:
```
Traceback (most recent call last):
  File "chromium.py", line 3, in <module>
    from telegram.ext import CommandHandler, Job, run_async
ImportError: No module named telegram.ext
```
How can i fix it?

**Comment by 1337w0rm** [comment]
Run ```pip install -r requirements.txt```

**Comment by eyjge** [comment]
@1337w0rm 
Yes,i run it already and i run it again,but the result still same
```
ubuntu@instance-20210712-1660:~/YeetMeet$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pause==0.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.2)
Requirement already satisfied: python_telegram_bot==12.5.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (12.5.1)
Requirement already satisfied: selenium==3.141.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (3.141.0)
Requirement already satisfied: psutil==5.7.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (5.7.2)
Requirement already satisfied: pylivestream==1.11.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.11.1)
Requirement already satisfied: tornado>=5.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from python_telegram_bot==12.5.1->-r requirements.txt (line 2)) (6.1)
Requirement already satisfied: decorator>=4.4.0 in /usr/local/lib/python3.8/dist-packages (from python_telegram_bot==12.5.1->-r requirements.txt (line 2)) (5.0.9)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from python_telegram_bot==12.5.1->-r requirements.txt (line 2)) (2019.11.28)
Requirement already satisfied: future>=0.16.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from python_telegram_bot==12.5.1->-r requirements.txt (line 2)) (0.18.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from python_telegram_bot==12.5.1->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium==3.141.0->-r requirements.txt (line 3)) (1.25.8)
ubuntu@instance-20210712-1660:~/YeetMeet$ python chromium.py
Traceback (most recent call last):
  File "chromium.py", line 3, in <module>
    from telegram.ext import CommandHandler, Job, run_async
ImportError: No module named telegram.ext
```
